# Generated by Django 2.2 on 2019-04-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemanager',
            name='user_name',
            field=models.CharField(default='', max_length=35, verbose_name='username'),
        ),
    ]
