# Generated by Django 2.1.2 on 2018-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=15, verbose_name='username')),
                ('user_phone', models.CharField(default='', max_length=15, verbose_name='cellphone number')),
                ('car_number', models.CharField(default='', max_length=10, verbose_name='Car number plate')),
                ('car_type', models.CharField(default='', max_length=11, verbose_name='Model')),
                ('car_color', models.CharField(default='', max_length=8, verbose_name='Car color')),
                ('car_comapany', models.CharField(default='', max_length=8, verbose_name='car company')),
            ],
            options={
                'verbose_name': 'User Info',
                'verbose_name_plural': 'User Info',
            },
        ),
    ]
