# Generated by Django 2.1.2 on 2018-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='car_booking_status',
            field=models.BooleanField(default=False, verbose_name='Bookking status [default is not Booked]'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_first_name',
            field=models.CharField(default='Chaman', max_length=15, verbose_name='Enter first name'),
        ),
    ]
