# Generated by Django 2.1.3 on 2018-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181103_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='admin_bit',
            field=models.BooleanField(default=False, verbose_name='Admin Bit'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='car_site_address',
            field=models.CharField(max_length=20, null=True, verbose_name='Site Number'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='car_slot_no',
            field=models.CharField(max_length=20, null=True, verbose_name='Slot Number'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='car_booking_status',
            field=models.BooleanField(default=False, verbose_name='Booking status'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='car_comapany',
            field=models.CharField(default='', max_length=8, verbose_name='Car company'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_phone',
            field=models.CharField(default='', max_length=10, verbose_name='cellphone number'),
        ),
    ]
