# Generated by Django 2.1.4 on 2018-12-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181215_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='car_comapany',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_first_name',
        ),
    ]
