# Generated by Django 2.1.2 on 2018-10-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_num', models.CharField(default='', max_length=20, verbose_name='Parking number')),
                ('position_status', models.BooleanField(default=True, verbose_name='Parking status [default is idle]')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_no', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='site number')),
                ('site_address', models.CharField(default='Mangalore', max_length=200)),
                ('pay_per_time', models.FloatField(default='15.0', verbose_name='cost')),
                ('max_capacity', models.IntegerField(default=0, verbose_name='Capacity')),
            ],
        ),
        migrations.AddField(
            model_name='positions',
            name='site_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carposition.Site'),
        ),
    ]
