# Generated by Django 2.1.2 on 2018-10-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Positions', 'verbose_name_plural': 'Positions'},
        ),
    ]
