# Generated by Django 2.2 on 2019-04-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='is_accountant',
            field=models.BooleanField(default=False, verbose_name='Accountant Bit'),
        ),
    ]
