# Generated by Django 2.1.2 on 2018-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='abc', max_length=20, verbose_name='user_name')),
                ('car_number', models.CharField(max_length=20, verbose_name='Plate Number')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='In Time')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='Out-Time')),
                ('parking_time', models.FloatField(default=0.0, editable=False, verbose_name='Parking time')),
                ('parking_money', models.FloatField(default=0.0, editable=False, verbose_name='parking fee')),
                ('ticket_type', models.CharField(choices=[('Hour', 'Hour ticket')], max_length=20, verbose_name='Billing type')),
                ('per_hour_money', models.FloatField(default=100.0, verbose_name='Hourly parking fees')),
            ],
            options={
                'verbose_name': 'Ticket Center',
                'verbose_name_plural': 'Ticket center',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('Hour', 'Hour ticket')], max_length=20, verbose_name='Billing type')),
                ('per_hour_money', models.FloatField(default=10.0, verbose_name='Hourly parking fee')),
            ],
            options={
                'verbose_name': 'Charge type',
                'verbose_name_plural': 'Charge type',
            },
        ),
    ]
