# Generated by Django 2.1.2 on 2018-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='site_add',
            field=models.CharField(default='', max_length=20, verbose_name='Site Address'),
        ),
    ]
